### ISSUE TITLE
Wrong glyph for U+00B0 DEGREE SIGN

### ISSUE THREAD

**Issue by dscorbett** [ctrlcctrlv/FRBAmericanCursive#1]
U+00B0 DEGREE SIGN is a filled-in disk. It should be a hollow circle. Here is ⟨0°⟩:
![0°](https://user-images.githubusercontent.com/1124347/108443021-0994c300-7226-11eb-88bd-9a06021ba819.png)

**Comment by ctrlcctrlv** [comment]
Thank you! Degree sign clearly needs added here: https://github.com/ctrlcctrlv/FRBAmericanCursive/blob/014c2e5f29914da2d28b65c3f7ee4fc7734d3ea9/scripts/gen_weight.py#L40-L41
