### ISSUE TITLE
Wrong glyph for U+00B5 MICRO SIGN

### ISSUE THREAD

**Issue by dscorbett** [ctrlcctrlv/FRBAmericanCursive#10]
The glyph for U+00B5 MICRO SIGN in version 1.2 looks more like a handwritten psi than a mu. The vertical stroke should be on the left and there should be an upturn as in ⟨u⟩ on the right.
![µ](https://user-images.githubusercontent.com/1124347/113515771-82d14680-9544-11eb-8b97-778202057eb7.png)

**Comment by ctrlcctrlv** [comment]
Does this look better, David?

3µg
![image](https://user-images.githubusercontent.com/838783/113516721-ced2ba00-9549-11eb-9a75-0f9deefcea61.png)

**Comment by dscorbett** [comment]
Yes.
