### ISSUE TITLE
Left-joining lowercase Cyrillic after uppercase Cyrillic

### ISSUE THREAD

**Issue by dscorbett** [ctrlcctrlv/FRBAmericanCursive#3]
In this font, uppercase Cyrillic letters are non-joining. Lowercase letters after them still take their left-joining forms, though there is nothing to join to. For example, here is Cyrillic ⟨Са⟩:
![Са](https://user-images.githubusercontent.com/1124347/108633073-4936f700-7440-11eb-950e-36495338a06d.png)
Cf. Latin ⟨Ca⟩:
![Ca](https://user-images.githubusercontent.com/1124347/108633089-5c49c700-7440-11eb-9290-8152f6fd21e5.png)
This is unlike how lowercase Cyrillic letters behave after other non-joining characters, as in ⟨-а⟩:
![-а](https://user-images.githubusercontent.com/1124347/108633432-34f3f980-7442-11eb-8aea-b147d8407105.png)

**Comment by ctrlcctrlv** [comment]
simoncozens/fontFeatures#30 is a blocker on this
