### ISSUE TITLE
Wrong shape of lowercase Cyrillic "ц"

### ISSUE THREAD

**Issue by murrrf** [ctrlcctrlv/FRBAmericanCursive#5]
The lowercase Cyrillic letter "ц" (U+0446) looks like a reduced copy of the capital "Ч" (U+0427), and not as the lower-case version of the capital "Ц" (U+0426).

**Comment by ctrlcctrlv** [comment]
Is ч also wrong?

**Comment by murrrf** [comment]
No, the "ч" is perfect.

Here is a piece of an illustration showing an example of modern Russian cursive.
![cursive.png](https://user-images.githubusercontent.com/4840415/113048550-57003a80-91ab-11eb-8793-648f067935ae.png)

**Comment by ctrlcctrlv** [comment]
OK, I recognize this as a bug. I'm not sure how it happened. Maybe I intended for the character currently occupying «ц» to occupy «ч» or «ч.salt» (Stylistic Alternates).

In any case, I'll move the current «ц» to «ч.salt» and draw a new shape for «ц».

**Comment by murrrf** [comment]
Thank you.
