### ISSUE TITLE
Bad overlap in U+00D8 LATIN CAPITAL LETTER O WITH STROKE

### ISSUE THREAD

**Issue by dscorbett** [ctrlcctrlv/FRBAmericanCursive#8]
U+00D8 LATIN CAPITAL LETTER O WITH STROKE looks wrong in version 1.2.
![Ø](https://user-images.githubusercontent.com/1124347/113493198-5c130180-94ab-11eb-9a73-b529e72a10d8.png)

**Comment by ctrlcctrlv** [comment]
Oh, I understand what happened here. I added a remove_internal feature to MFEKstroke, and forgot to whitelist `Oslash`. At first I was thinking this was a fontmake overlap bug. I'll try to remember to do a rebuild for you tomorrow, I'm too tired tonight, it takes around twenty minutes on my laptop to run through the whole build, it's a complicated build.
